version: '2'
services:
  lazyservice-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/lazyservice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lazyservice
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
